# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clawpipeline < Formula
  desc "Agent 产物回传流水线，支持重试、幂等与审计追踪"
  homepage "https://github.com/hooziwang/ClawPipeline"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/ClawPipeline/releases/download/v0.2.3/clawpipeline_0.2.3_darwin_amd64.tar.gz"
      sha256 "51c310ae4020072b7bfa4001c78296043ed93d8d33b58cd669ca19bfdcc3b46e"

      def install
        bin.install "clawpipeline"
        bin.install "clawpipelined"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/ClawPipeline/releases/download/v0.2.3/clawpipeline_0.2.3_darwin_arm64.tar.gz"
      sha256 "10d51c3678499b33d8eb415a1f595f510cfa718d4a411c24eb509f84c481b5e4"

      def install
        bin.install "clawpipeline"
        bin.install "clawpipelined"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/ClawPipeline/releases/download/v0.2.3/clawpipeline_0.2.3_linux_amd64.tar.gz"
      sha256 "29348ad6bd5e0305dc75ff8d0748a957bb45a1047f7123268cc7f39287d25de0"
      def install
        bin.install "clawpipeline"
        bin.install "clawpipelined"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/ClawPipeline/releases/download/v0.2.3/clawpipeline_0.2.3_linux_arm64.tar.gz"
      sha256 "36408834f358fc1de14fd78cdba11dd48931f41c7a48018fcb9c1823b4b1283a"
      def install
        bin.install "clawpipeline"
        bin.install "clawpipelined"
      end
    end
  end

  test do
    system "#{bin}/clawpipeline", "version"
    system "#{bin}/clawpipelined", "--version"
  end
end
