# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MunaVideoGoogle < Formula
  desc "使用 Gemini API 生成视频的命令行工具"
  homepage "https://github.com/hooziwang/muna-video-google"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/muna-video-google/releases/download/v0.1.2/muna-video-google_0.1.2_darwin_amd64.tar.gz"
      sha256 "ca9eee4af3f6facf8e46adb18eb94559f0eeacbe35db1fd935e9b899d7f765e0"

      def install
        bin.install "muna-video-google"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/muna-video-google/releases/download/v0.1.2/muna-video-google_0.1.2_darwin_arm64.tar.gz"
      sha256 "da32806cdfb389e75e980f2c3d1b2dfc39e27fe6f803aac6f0452ab322d4f5b5"

      def install
        bin.install "muna-video-google"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/muna-video-google/releases/download/v0.1.2/muna-video-google_0.1.2_linux_amd64.tar.gz"
      sha256 "1472d58b681bdff4e3944f0b16437eba92d4c8b127e63271e03c6ad4441eb897"
      def install
        bin.install "muna-video-google"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/muna-video-google/releases/download/v0.1.2/muna-video-google_0.1.2_linux_arm64.tar.gz"
      sha256 "cc36470a551272adffad48c944ee5e18e592cf90932a142e17b71b1864a3dfd9"
      def install
        bin.install "muna-video-google"
      end
    end
  end

  test do
    system "#{bin}/muna-video-google", "--help"
  end
end
