# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MunaImageGoogle < Formula
  desc "使用 Gemini API 生成图像的命令行工具"
  homepage "https://github.com/hooziwang/muna-image-google"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/muna-image-google/releases/download/v0.2.1/muna-image-google_0.2.1_darwin_amd64.tar.gz"
      sha256 "ef5f44d4f9c1eadafe33295ef69e9b2e3671fb74174e580250baaea2becf9552"

      def install
        bin.install "muna-image-google"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/muna-image-google/releases/download/v0.2.1/muna-image-google_0.2.1_darwin_arm64.tar.gz"
      sha256 "5f5202d30614a0dedaecb200af6645745fea8d7bfe42cb0245c74d4cf710dab4"

      def install
        bin.install "muna-image-google"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/muna-image-google/releases/download/v0.2.1/muna-image-google_0.2.1_linux_amd64.tar.gz"
      sha256 "2b29294872b993f01753971bbc3f08fed1d3847a580a948364a8b5244bccff05"
      def install
        bin.install "muna-image-google"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/muna-image-google/releases/download/v0.2.1/muna-image-google_0.2.1_linux_arm64.tar.gz"
      sha256 "cb4dc94c262734189f815464206c97daa4d53bbda1acaaeb320d0936c12354ed"
      def install
        bin.install "muna-image-google"
      end
    end
  end

  test do
    system "#{bin}/muna-image-google", "--help"
  end
end
