# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylListingPro < Formula
  desc "多租户亚马逊 Listing 双语生成 CLI"
  homepage "https://github.com/hooziwang/syl-listing-pro"
  version "0.1.8"

  depends_on "pandoc"
  depends_on "syl-md2doc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-listing-pro/releases/download/v0.1.8/syl-listing-pro_0.1.8_darwin_amd64.tar.gz"
      sha256 "261617bad777a6109e822ffc31cfe52c46fca6cb22dd2e76ece945428e08b353"

      define_method(:install) do
        bin.install "syl-listing-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-listing-pro/releases/download/v0.1.8/syl-listing-pro_0.1.8_darwin_arm64.tar.gz"
      sha256 "780537a7d06ff66e6c6185360a19cec9fb49ade6ba511025692eb447b6aa2ec3"

      define_method(:install) do
        bin.install "syl-listing-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing-pro/releases/download/v0.1.8/syl-listing-pro_0.1.8_linux_amd64.tar.gz"
      sha256 "675d33f0ebbe51dc82c8b6c624977ef5ea0ee77e14eb21e33b3eda531769b9dc"
      define_method(:install) do
        bin.install "syl-listing-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing-pro/releases/download/v0.1.8/syl-listing-pro_0.1.8_linux_arm64.tar.gz"
      sha256 "4945dd03fcbdce34b8a601f923b7772f997636b8249384ca7dbcb082ea08531e"
      define_method(:install) do
        bin.install "syl-listing-pro"
      end
    end
  end

  test do
    system "#{bin}/syl-listing-pro", "--version"
  end
end
