# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylMd2doc < Formula
  desc "把 Markdown 文件批量转换为 Word(docx) 的命令行工具"
  homepage "https://github.com/hooziwang/syl-md2doc"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.3.0/syl-md2doc_0.3.0_darwin_amd64.tar.gz"
      sha256 "83587e75a995d818a58927e826228d388ff4e1393fe30d77bfb5b43ed3dfcd74"

      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.3.0/syl-md2doc_0.3.0_darwin_arm64.tar.gz"
      sha256 "66b406215634446e869311e77d987253051bc9e7f6d3c685f406978f50f47d9d"

      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.3.0/syl-md2doc_0.3.0_linux_amd64.tar.gz"
      sha256 "338f021c184dadf46040d0dc8336445247199045c744cca0c369817f520e4a2a"
      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.3.0/syl-md2doc_0.3.0_linux_arm64.tar.gz"
      sha256 "929a7bff75248dfb1b19843b50249dca8fb18926d37999842895aacf2174b92f"
      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
  end

  test do
    system "#{bin}/syl-md2doc", "--version"
  end
end
