# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylWordcount < Formula
  desc "面向 AI 的文本统计与规则校验 CLI"
  homepage "https://github.com/hooziwang/syl-wordcount"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-wordcount/releases/download/v1.0.0/syl-wordcount_1.0.0_darwin_amd64.tar.gz"
      sha256 "286d9d705804132133ab4b4e9b6521a367174efd7952455939bcc455d2a185b6"

      define_method(:install) do
        bin.install "syl-wordcount"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-wordcount/releases/download/v1.0.0/syl-wordcount_1.0.0_darwin_arm64.tar.gz"
      sha256 "3ed999609476cb78a3ba58cfec9dea8513a3a88015c2a13aa7fc82f9f77e6822"

      define_method(:install) do
        bin.install "syl-wordcount"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-wordcount/releases/download/v1.0.0/syl-wordcount_1.0.0_linux_amd64.tar.gz"
      sha256 "92045d5afaf94e6406f0fd8e8afde45cfdcd94e70befaacf3985c582f2a89825"
      define_method(:install) do
        bin.install "syl-wordcount"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-wordcount/releases/download/v1.0.0/syl-wordcount_1.0.0_linux_arm64.tar.gz"
      sha256 "f63754105e4c8d0b74901c413badda00b93144d58bf6cc7ba7e91cca61b95ded"
      define_method(:install) do
        bin.install "syl-wordcount"
      end
    end
  end

  test do
    system "#{bin}/syl-wordcount", "--version"
  end
end
