# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylListing < Formula
  desc "基于 Go + Cobra 的 Amazon Listing 中英双语生成工具"
  homepage "https://github.com/hooziwang/syl-listing"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.1/syl-listing_0.1.1_darwin_amd64.tar.gz"
      sha256 "07c8c679df24e3a2f664638454335cd9b1a33ba0dbe7a7e4da2e2af82f67e0f6"

      define_method(:install) do
        bin.install "syl-listing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.1/syl-listing_0.1.1_darwin_arm64.tar.gz"
      sha256 "cb9dd3084ab65c7300f58235b0efdb7423b89262def7660c21de4ff12d676540"

      define_method(:install) do
        bin.install "syl-listing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.1/syl-listing_0.1.1_linux_amd64.tar.gz"
      sha256 "11f06cf1d901e1cfe290ecc46129c4dcf5a5a136d0079587b2203fe8bc1a665e"
      define_method(:install) do
        bin.install "syl-listing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.1/syl-listing_0.1.1_linux_arm64.tar.gz"
      sha256 "c983539763a17498279c160558e4158054ee09df226a9741e716ebbef3f0d7bd"
      define_method(:install) do
        bin.install "syl-listing"
      end
    end
  end

  test do
    system "#{bin}/syl-listing", "--version"
  end
end
