# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylMd2ppt < Formula
  desc "把 EN/CN Markdown 一键转换为单个双语 PPTX 的命令行工具"
  homepage "https://github.com/hooziwang/syl-md2ppt"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.6/syl-md2ppt_1.0.6_darwin_amd64.tar.gz"
      sha256 "dead5cd2b6f64ad3f1481b86ded61f030878ac99ff14b3248f3189727b994427"

      def install
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.6/syl-md2ppt_1.0.6_darwin_arm64.tar.gz"
      sha256 "174d5cf306f638b0c4bcbe0325d2224221885fbeecc0d39ae317cfcc2f80a320"

      def install
        bin.install "syl-md2ppt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.6/syl-md2ppt_1.0.6_linux_amd64.tar.gz"
      sha256 "eb929b9056395b177fa45dbb4592e6c3d4cd06f6d1f09b1679edd6661c0568b4"
      def install
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.6/syl-md2ppt_1.0.6_linux_arm64.tar.gz"
      sha256 "06219f43aea876553780f7752570978229f1e1d6a0a5918d291580f1bbd4d08a"
      def install
        bin.install "syl-md2ppt"
      end
    end
  end

  test do
    system "#{bin}/syl-md2ppt", "--version"
  end
end
