# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylMd2doc < Formula
  desc "把 Markdown 文件批量转换为 Word(docx) 的命令行工具"
  homepage "https://github.com/hooziwang/syl-md2doc"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.2.0/syl-md2doc_0.2.0_darwin_amd64.tar.gz"
      sha256 "658b6244025805f6dbffab1c198b1d4b3f16090b596db007252187f23a94b6b9"

      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.2.0/syl-md2doc_0.2.0_darwin_arm64.tar.gz"
      sha256 "a95c151b1616bb1f26ba1893786495eee9e0097d22b97f6b076cab85afd0e7c6"

      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.2.0/syl-md2doc_0.2.0_linux_amd64.tar.gz"
      sha256 "c63b1f02d2ca8aeb8e7adf3b3d54763824b8d3b6c3ac759a05e365a7d320dd49"
      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2doc/releases/download/v0.2.0/syl-md2doc_0.2.0_linux_arm64.tar.gz"
      sha256 "58b258b5b76d052eaba725edf9fbb1f7c638992ef78a6b1b706466fa7336c359"
      define_method(:install) do
        bin.install "syl-md2doc"
      end
    end
  end

  test do
    system "#{bin}/syl-md2doc", "--version"
  end
end
