# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylMd2ppt < Formula
  desc "把 EN/CN Markdown 一键转换为单个双语 PPTX 的命令行工具"
  homepage "https://github.com/hooziwang/syl-md2ppt"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.7/syl-md2ppt_1.0.7_darwin_amd64.tar.gz"
      sha256 "284e6a7b0dcc1a8746eca3aa1ace8a63843dcea72d5a749d77de80358008af8c"

      define_method(:install) do
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.7/syl-md2ppt_1.0.7_darwin_arm64.tar.gz"
      sha256 "0a6a2a6f3ad42d1b579ae4202c66b881db924e015c948f4a4109ea99909e93c8"

      define_method(:install) do
        bin.install "syl-md2ppt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.7/syl-md2ppt_1.0.7_linux_amd64.tar.gz"
      sha256 "e1c0eb2b3c8eee0d1769c3f4788e8f8f847b50819e9213e21a71b6423e01e99b"
      define_method(:install) do
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.7/syl-md2ppt_1.0.7_linux_arm64.tar.gz"
      sha256 "646050fa3fc8cb0d382e0642c87aabecf4c2a847d799b552bf062143405fe200"
      define_method(:install) do
        bin.install "syl-md2ppt"
      end
    end
  end

  test do
    system "#{bin}/syl-md2ppt", "--version"
  end
end
