# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylListing < Formula
  desc "基于 Go + Cobra 的 Amazon Listing 中英双语生成工具"
  homepage "https://github.com/hooziwang/syl-listing"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.0/syl-listing_0.1.0_darwin_amd64.tar.gz"
      sha256 "f948ea51c76798b91dcafc413557dc42154aba93ad27a5c62bc57921747af6f6"

      define_method(:install) do
        bin.install "syl-listing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.0/syl-listing_0.1.0_darwin_arm64.tar.gz"
      sha256 "043c3bcf3e174abe34c873ca685faa83965a269bf09cc0d8d159e8db7d538b23"

      define_method(:install) do
        bin.install "syl-listing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.0/syl-listing_0.1.0_linux_amd64.tar.gz"
      sha256 "725f7fc073f06f09e26238b2758aff8628ced3cf00e91ea92e71de13a093b8ef"
      define_method(:install) do
        bin.install "syl-listing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-listing/releases/download/v0.1.0/syl-listing_0.1.0_linux_arm64.tar.gz"
      sha256 "a7f9263e4299278e41b06b71fde080dcee89ccb8df5f438b50cd3e195d235ccd"
      define_method(:install) do
        bin.install "syl-listing"
      end
    end
  end

  test do
    system "#{bin}/syl-listing", "--version"
  end
end
