# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SylMd2ppt < Formula
  desc "把 EN/CN Markdown 一键转换为单个双语 PPTX 的命令行工具"
  homepage "https://github.com/hooziwang/syl-md2ppt"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.3/syl-md2ppt_1.0.3_darwin_amd64.tar.gz"
      sha256 "80fd08a6b249f5ccd4732998591b8fec0932c3b7c54c62f226329644f4c15dcc"

      def install
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.3/syl-md2ppt_1.0.3_darwin_arm64.tar.gz"
      sha256 "cbe9ba2008e46b28ffad8a375f8798c5f705279ee107698962962f76871d995c"

      def install
        bin.install "syl-md2ppt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.3/syl-md2ppt_1.0.3_linux_amd64.tar.gz"
      sha256 "72f84816517d457dfb13f5f205e9637f380321f728dc1376dff9f694a5322343"
      def install
        bin.install "syl-md2ppt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hooziwang/syl-md2ppt/releases/download/v1.0.3/syl-md2ppt_1.0.3_linux_arm64.tar.gz"
      sha256 "5afa299a629fbcc2a2ff32f4f94b51556bc40e041deb1b3e816ebc7d9be30a02"
      def install
        bin.install "syl-md2ppt"
      end
    end
  end

  test do
    system "#{bin}/syl-md2ppt", "--version"
  end
end
